apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: providers.cloudkinds.k8s.io
spec:
  group: cloudkinds.k8s.io
  names:
    kind: Provider
    plural: providers
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            kinds:
              items:
                type: string
              type: array
            webhook:
              type: string
          required:
          - webhook
          - kinds
          type: object
        status:
          type: object
  version: v1alpha1
