apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloudkinds-controller
rules:
- apiGroups:
  - cloudkinds.k8s.io
  resources:
  - providers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloudkinds.k8s.io
  resources:
  - cloudresources
  verbs:
  - get
  - list
  - watch
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: cloudkinds-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cloudkinds-controller
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
