# Default values for cloudkinds.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: carolynvs/cloudkinds
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

sampleProvider:
  include: true
  image:
    repository: carolynvs/cloudkinds-sampleprovider
    tag: latest
    pullPolicy: Always

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
