apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - cloudkinds.k8s.io
  resources:
  - providers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloudkinds.k8s.io
  resources:
  - cloudresources
  verbs:
  - get
  - list
  - watch
  - update
  - patch
